[versions]
lamp = "4.0.0-rc.16"
adventure = "4.25.0"
packetevents = "2.11.2"
jackson = "2.20.1"
creative = "1.11.8"
paper = "1.21.11-R0.1-SNAPSHOT"

[libraries]
passport = { group = "me.combimagnetron", name = "Passport", version = "1.0-SNAPSHOT" }
paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
# --- Minecraft ---
# Lamp Command Framework
lamp-common = { group = "io.github.revxrsal", name = "lamp.common", version.ref = "lamp" }
lamp-paper = { group = "io.github.revxrsal", name = "lamp.bukkit", version.ref = "lamp" }
lamp-brigadier = { group = "io.github.revxrsal", name = "lamp.brigadier", version.ref = "lamp" }
lamp-minestom = { group = "io.github.revxrsal", name = "lamp.minestom", version.ref = "lamp" }
# Kyori Adenture text shizzle
adventure-api = { group = "net.kyori", name = "adventure-api", version.ref = "adventure" }
adventure-gson = { group = "net.kyori", name = "adventure-text-serializer-gson", version.ref = "adventure" }
adventure-plain = { group = "net.kyori", name = "adventure-text-serializer-plain", version.ref = "adventure" }
# Packetevents
packetevents = { group = "com.github.retrooper", name = "packetevents-spigot", version.ref = "packetevents" }
# Creative resourcepack
creative-api = { group = "team.unnamed", name = "creative-api", version.ref = "creative" }
creative-serializer-minecraft = { group = "team.unnamed", name = "creative-serializer-minecraft", version.ref = "creative" }

# --- Config ---
sponge-yaml = { group = "org.spongepowered", name = "configurate-yaml", version = "4.2.0" }

# --- Utils ---
guava = { group = "com.google.guava", name = "guava", version = "31.1-jre" }
commons3 = { group = "org.apache.commons", name = "commons-lang3", version = "3.17.0" }
commons-io = { group = "commons-io", name = "commons-io", version = "2.18.0" }
commons-compress = { group = "org.apache.commons", name = "commons-compress", version = "1.28.0" }
caffeine = { group =  "com.github.ben-manes.caffeine", name = "caffeine", version ="3.2.0" }
fastutil = { group = "it.unimi.dsi", name = "fastutil", version = "8.5.16" }
jackson = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson" }
jackson-xml = { group = "com.fasterxml.jackson.dataformat", name = "jackson-dataformat-xml", version.ref = "jackson" }
annotations = { group = "org.jetbrains", name = "annotations", version = "26.0.2" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version = "5.3.2" }
joml = { group = "org.joml", name = "joml", version = "1.10.8" }

# --- Build Logic Hacks ---
build-system-license = { group = "com.github.hierynomus.license", name = "com.github.hierynomus.license.gradle.plugin", version = "0.16.1" }
build-system-license-base = { group = "com.github.hierynomus.license-base", name = "com.github.hierynomus.license-base.gradle.plugin", version = "0.16.1" }

[bundles]
minecraft = ["creative-api", "creative-serializer-minecraft"]
adventure = ["adventure-api", "adventure-gson", "adventure-plain"]
utils = ["guava", "commons3", "commons-io", "caffeine", "fastutil", "jackson", "commons-compress", "jackson-xml", "annotations", "okhttp", "joml"]
lamp-command = ["lamp-common", "lamp-paper", "lamp-minestom"]
